// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Starcraft.Stat.DataBase;

#nullable disable

namespace Starcraft.Stat.Migrations
{
    [DbContext(typeof(StarcraftDbContext))]
    partial class StarcraftDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Starcraft.Stat.Models.Race", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("Race");

                    b.HasData(
                        new
                        {
                            Name = "Terran"
                        },
                        new
                        {
                            Name = "Zerg"
                        },
                        new
                        {
                            Name = "Protoss"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
